
 
    <main>
        <section>
           <form action="add_article.php" method="POST">
                <input type="submit" value="+ Nouvel article" class="btn">
            </form>
            <caption>Liste des articles</caption>
            <table>
            <thead>
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Image</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
                <tbody>
                <?php foreach ($articles as $article): ?>
                    <tr id="article-<?=htmlspecialchars($article['id']);?>">
                        <td><?=htmlspecialchars($article['title']);?></td>
                        <td><?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></td>
                        <td>
                            <?php if ($article['image']): ?>
                                <img src="images/<?=$article['image'];?>" alt="">
                            <?php endif; ?>
                        </td>
                        <td>
                            <a href="edit_article.php?id=<?=$article['id'];?>"><i class="fa-solid fa-pen-to-square"></i> Modifier</a>
                         
                            <a class="delete-article-button"  data-ajax="delete_article_ajax.php?id=<?=htmlspecialchars($article['id']);?>"    href="delete_article.php?id=<?=htmlspecialchars($article['id']);?>"><i class="fa-solid fa-trash-can"></i> Supprimer</a>
                            
                            
                         </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </section>
    
    </main>
