
    <a href="<?=buildUrl('addArt');?>" title="Ajouter un nouvel article">Ajouter un article</a>


    <main>

        <section>
           <form action="<?=buildUrl('addArt');?>" method="POST">
                <input type="submit" value="+ Nouvel article" class="btn">
            </form>
            <caption>Liste des articles</caption>
            <table>
            <thead>
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Image</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
                <tbody>
                <?php foreach ($articles as $article): ?>
                    <tr id="article-<?=htmlspecialchars($article['idArticle']);?>">
                        <td><?=htmlspecialchars($article['title']);?></td>
                        <td><?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></td>
                        <td>
                            <?php if ($article['image']): ?>
                                <img src="images/<?=$article['image'];?>" alt="">
                            <?php endif; ?>
                        </td>
                        <td>
                            <a href="<?= buildUrl('editArt',['id' => $article['idArticle']])?>"><i class="fa-solid fa-pen-to-square"></i> Modifier</a>
                            
                            <a class="delete-article-button" 
                       href="<?=buildUrl('delArt', ['id' => intval($article['idArticle'])]);?>"
                       data-ajax="<?=buildUrl('delArtAjax', ['id' => intval($article['idArticle'])]);?>"><i class="fa-solid fa-trash-can"></i> Supprimer</a>
               


                         </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </section>
    
    </main>
    