<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php if (isset($css)):?>
        <?= $css;?>
    <?php endif;?>
    <title>Mon Super Blog </title>
</head>
<body>
    <header>
        <h1><?= $titlePage;?></h1>
        <nav>
            <?php
                if (isConnected()) { 
                    ?>
                        <a href="logout.php">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion</a>
                         <p> Bonjour <?=htmlspecialchars($_SESSION['user']['firstname']);?>  <?=$_SESSION['user']['lastname'];?> </p>
                    <?php    
                } else {
                    ?>
                    <a href="login.php">Connexion</a>
                    <a href="signup.php">Créer un compte</a>
                    <?php 
                }
            ?>
        </nav>
    </header>
    <main>
        <?php
            include '../templates/'.$template.'.phtml';
        ?>
    </main>
</body>
</html>