    
    <main>
        <section>
            <h2>Les derniers articles</h2>
            
            <?php foreach ($articles as $article): ?>
                <article>
                    <h3><?=$article['title'];?></h3>
                    <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d-m-Y');?></small>
                    <p><?=$article['abstract']?$article['abstract']:substr($article['content'],0,150).' [...]';?> </p>
 
                    <?php if ($article['image']): ?>
                        <img src="images/<?=$article['image'];?>" alt="">
                    <?php endif; ?>

                        <a href="<?= buildUrl('article',['id' => $article['idArticle']])?>">Lire la suite</a>

                </article>
            <?php // } ?>
            <?php endforeach; ?>
        </section>
     
        <p><?php if (isConnected()): ?>
                <p>Utilisation hmltspecialchars <?= htmlspecialchars($_SESSION['user']['firstname']);?></p>
                <?=$_SESSION['user']['firstname'];?>
            <?php endif; ?>
        </p>
    </main>
