<main>
        <form method="POST" action="signup.php">
            <fieldset>
                <legend>Création de compte</legend>
                <div>
                    <label for="firstname">Prénom</label>
                    <input type="text" id="firstname" name="firstname" value="<?=$firstname;?>">
                    <?php if (isset($errors['firstname'])): ?>
                        <p class="error"><?=$errors['firstname'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="lastname">Nom</label>
                    <input type="text" id="lastname" name="lastname" value="<?=$lastname;?>">
                    <?php if (isset($errors['lastname'])): ?>
                        <p class="error"><?=$errors['lastname'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="email">Email</label>
                    <input type="text" id="email" name="email" value="<?=$email;?>" >
                    <?php if (isset($errors['email'])): ?>
                        <p class="error"><?=$errors['email'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="password">Mot de passe</label>
                    <input type="text" id="password" name="password">
                    <?php if (isset($errors['password'])): ?>
                        <p class="error"><?=$errors['password'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="password_confirm">Mot de passe (confirmation)</label>
                    <input type="text" id="password_confirm" name="password_confirm">
                    <?php if (isset($errors['password_confirm'])): ?>
                        <p class="error"><?=$errors['password_confirm'];?></p>
                    <?php endif; ?>
                </div>
                <input type="submit" value="Confirmer">
            </fieldset>
        </form>
        <div>
            <?php 
                foreach ($errors as $error) :?>
                    <p class="error"><?=$error;?></p>
                <?php endforeach; ?> 
        </div>
    </main>